apiVersion: v1
kind: Pod
metadata:
  name: mywebapp
  apiVersion: v1
  namespace: roboshop
  labels:
    role: webserver-role
    app: nginx
spec:
  containers:
  - name: webserver
    image: nginx:1.6
    ports:
     - containerPort:80